package progsistemas;




import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Meu computador
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        EditorPane = new javax.swing.JTextPane();
        EditorExe = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Opcoes = new javax.swing.JMenu();
        AbrirMenu = new javax.swing.JMenuItem();
        Salvar = new javax.swing.JMenuItem();
        clrEditor = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MontadorPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MontadorIn = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        MontadorOut = new javax.swing.JTextArea();
        MacroPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MacroDef = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        MacroExp = new javax.swing.JTextArea();
        CarregadorPane = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        CodCarregado = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        LigadorPane = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        CodLigado = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        MaquinaPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CodCompleto = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Reg = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuOpExe = new javax.swing.JMenuItem();
        MenuReset = new javax.swing.JMenuItem();
        MenuExt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuHelpButton = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("68K Assembler Runtime Simulator");
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jInternalFrame1.setVisible(true);

        jScrollPane10.setViewportView(EditorPane);

        EditorExe.setText("Executar");
        EditorExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorExeActionPerformed(evt);
            }
        });

        Opcoes.setText("Opções");

        AbrirMenu.setText("Abrir no Editor");
        AbrirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirMenuActionPerformed(evt);
            }
        });
        Opcoes.add(AbrirMenu);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        Opcoes.add(Salvar);

        clrEditor.setText("Limpar Tela");
        clrEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrEditorActionPerformed(evt);
            }
        });
        Opcoes.add(clrEditor);

        jMenuBar2.add(Opcoes);

        jInternalFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorExe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorExe)
                .addGap(536, 536, 536))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap(58, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("Editor", jInternalFrame1);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        MontadorPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Entrada do Montador");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Código Montado");

        MontadorIn.setEditable(false);
        MontadorIn.setColumns(20);
        MontadorIn.setRows(5);
        jScrollPane2.setViewportView(MontadorIn);

        MontadorOut.setEditable(false);
        MontadorOut.setColumns(20);
        MontadorOut.setRows(5);
        jScrollPane5.setViewportView(MontadorOut);

        javax.swing.GroupLayout MontadorPaneLayout = new javax.swing.GroupLayout(MontadorPane);
        MontadorPane.setLayout(MontadorPaneLayout);
        MontadorPaneLayout.setHorizontalGroup(
            MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MontadorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MontadorPaneLayout.createSequentialGroup()
                        .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(MontadorPaneLayout.createSequentialGroup()
                        .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 462, Short.MAX_VALUE))))
        );
        MontadorPaneLayout.setVerticalGroup(
            MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MontadorPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Montador", MontadorPane);

        MacroPane.setBackground(new java.awt.Color(255, 255, 255));

        MacroDef.setEditable(false);
        MacroDef.setColumns(20);
        MacroDef.setRows(5);
        jScrollPane1.setViewportView(MacroDef);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Macros Definidas");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Macros Expandidas");

        MacroExp.setEditable(false);
        MacroExp.setColumns(20);
        MacroExp.setRows(5);
        jScrollPane6.setViewportView(MacroExp);

        javax.swing.GroupLayout MacroPaneLayout = new javax.swing.GroupLayout(MacroPane);
        MacroPane.setLayout(MacroPaneLayout);
        MacroPaneLayout.setHorizontalGroup(
            MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MacroPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addGroup(MacroPaneLayout.createSequentialGroup()
                        .addGroup(MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MacroPaneLayout.setVerticalGroup(
            MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MacroPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Process. de Macros", MacroPane);

        CarregadorPane.setBackground(new java.awt.Color(255, 255, 255));

        CodCarregado.setEditable(false);
        jScrollPane7.setViewportView(CodCarregado);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Código Carregado");

        javax.swing.GroupLayout CarregadorPaneLayout = new javax.swing.GroupLayout(CarregadorPane);
        CarregadorPane.setLayout(CarregadorPaneLayout);
        CarregadorPaneLayout.setHorizontalGroup(
            CarregadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregadorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarregadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(CarregadorPaneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 702, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CarregadorPaneLayout.setVerticalGroup(
            CarregadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarregadorPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carregador", CarregadorPane);

        LigadorPane.setBackground(new java.awt.Color(255, 255, 255));

        CodLigado.setEditable(false);
        jScrollPane8.setViewportView(CodLigado);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Código Ligado");

        javax.swing.GroupLayout LigadorPaneLayout = new javax.swing.GroupLayout(LigadorPane);
        LigadorPane.setLayout(LigadorPaneLayout);
        LigadorPaneLayout.setHorizontalGroup(
            LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LigadorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(LigadorPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 733, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LigadorPaneLayout.setVerticalGroup(
            LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LigadorPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ligador", LigadorPane);

        MaquinaPane.setBackground(new java.awt.Color(255, 255, 255));

        CodCompleto.setEditable(false);
        CodCompleto.setColumns(20);
        CodCompleto.setRows(5);
        jScrollPane3.setViewportView(CodCompleto);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Código Completo");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Registradores");

        Reg.setEditable(false);
        Reg.setColumns(20);
        Reg.setRows(5);
        jScrollPane9.setViewportView(Reg);

        javax.swing.GroupLayout MaquinaPaneLayout = new javax.swing.GroupLayout(MaquinaPane);
        MaquinaPane.setLayout(MaquinaPaneLayout);
        MaquinaPaneLayout.setHorizontalGroup(
            MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaquinaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaquinaPaneLayout.createSequentialGroup()
                        .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        MaquinaPaneLayout.setVerticalGroup(
            MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaquinaPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maquina", MaquinaPane);

        jTabbedPane.addTab("        Executado        ", jTabbedPane1);

        Title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/68kas_logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Arquivo");

        MenuOpExe.setText("Abrir e Executar");
        MenuOpExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpExeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuOpExe);

        MenuReset.setText("Resetar");
        MenuReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuResetActionPerformed(evt);
            }
        });
        jMenu1.add(MenuReset);

        MenuExt.setText("Sair");
        MenuExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExtActionPerformed(evt);
            }
        });
        jMenu1.add(MenuExt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        MenuHelpButton.setText("Ajuda");
        MenuHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpButtonActionPerformed(evt);
            }
        });
        jMenu2.add(MenuHelpButton);
        MenuHelpButton.getAccessibleContext().setAccessibleName("Ajuda");

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpButtonActionPerformed
        Help frame = new Help();
        frame.setVisible(true);
    }//GEN-LAST:event_MenuHelpButtonActionPerformed

    private void MenuOpExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpExeActionPerformed
        Principal p = null;
        
        //Leitura do nome do arquivo
        String arq = JOptionPane.showInputDialog(null, "Digite o nome do arquivo de entrada", "Arquivo", JOptionPane.QUESTION_MESSAGE);
        while (arq == null || arq.equals("")) {
            arq = JOptionPane.showInputDialog(null, "Digite novamente o nome do arquivo de entrada", "Erro: nome inválido", JOptionPane.ERROR_MESSAGE);
        }
        
        //Puxar o arquivo do novo endereço para a classe Principal
        try {
            p = new Principal(arq);
        } catch (IOException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MontadorIn.setText(p.getInArq());
        MontadorOut.setText(p.getOutArq());
        JOptionPane.showMessageDialog(null, "O arquivo foi executado com sucesso!", "Arquivo Pronto", 1, null);
    }//GEN-LAST:event_MenuOpExeActionPerformed

    private void MenuResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuResetActionPerformed
        MontadorIn.setText("");
        MontadorOut.setText("");
        MacroDef.setText("");
        MacroExp.setText("");
        CodCarregado.setText("");
        CodLigado.setText("");
        CodCompleto.setText("");
        Reg.setText("");
    }//GEN-LAST:event_MenuResetActionPerformed

    private void MenuExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExtActionPerformed
        dispose();
    }//GEN-LAST:event_MenuExtActionPerformed

    private void clrEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrEditorActionPerformed
        EditorPane.setText("");
    }//GEN-LAST:event_clrEditorActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        String instr = EditorPane.getText();

        if(instr.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sem instrucoes para processar. Favor digitar o codigo", "Erro: sem instrucoes", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Principal p = null;
            String arqPath = JOptionPane.showInputDialog(null, "Digite o nome do arquivo", "Salvar", JOptionPane.QUESTION_MESSAGE);

            Save s = null;
            try {
                s = new Save(instr, arqPath);
                JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso!", "Salvo", 1, null);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void AbrirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirMenuActionPerformed
        Principal p = null;

        //Leitura do nome do arquivo
        String arq = JOptionPane.showInputDialog(null, "Digite o nome do arquivo de entrada", "Arquivo", JOptionPane.QUESTION_MESSAGE);
        while (/*arq != null || */ arq.equals("")) {
            arq = JOptionPane.showInputDialog(null, "Digite novamente o nome do arquivo de entrada", "Erro: nome inválido", JOptionPane.ERROR_MESSAGE);
        }

        //Puxar o arquivo do novo endereço para a classe Principal
        try {
            p = new Principal(arq);
        } catch (IOException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        EditorPane.setText(p.getInArq());
    }//GEN-LAST:event_AbrirMenuActionPerformed

    private void EditorExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorExeActionPerformed
        String instr = EditorPane.getText();

        if(instr.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sem instrucoes para processar. Favor digitar o codigo", "Erro: sem instrucoes", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Principal p = null;
            String arqPath = "aux";

            Save s = null;
            try {
                s = new Save(instr, arqPath);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                p = new Principal(s.fileName());
                JOptionPane.showMessageDialog(null, "Codigo executado com exito", "Executado", 1, null);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            MontadorIn.setText("");
            MontadorOut.setText("");
            MontadorIn.setText(p.getInArq());
            MontadorOut.setText(p.getOutArq());

        }
    }//GEN-LAST:event_EditorExeActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JOptionPane.showMessageDialog(null, "Simulador do Motorola 68k v. 1.0 (68K.A.R.S)", "Bem-vindo!", 1, null);
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirMenu;
    private javax.swing.JPanel CarregadorPane;
    private javax.swing.JTextPane CodCarregado;
    private javax.swing.JTextArea CodCompleto;
    private javax.swing.JTextPane CodLigado;
    private javax.swing.JButton EditorExe;
    private javax.swing.JTextPane EditorPane;
    private javax.swing.JPanel LigadorPane;
    private javax.swing.JTextArea MacroDef;
    private javax.swing.JTextArea MacroExp;
    private javax.swing.JPanel MacroPane;
    private javax.swing.JPanel MaquinaPane;
    private javax.swing.JMenuItem MenuExt;
    private javax.swing.JMenuItem MenuHelpButton;
    private javax.swing.JMenuItem MenuOpExe;
    private javax.swing.JMenuItem MenuReset;
    private javax.swing.JTextArea MontadorIn;
    private javax.swing.JTextArea MontadorOut;
    private javax.swing.JPanel MontadorPane;
    private javax.swing.JMenu Opcoes;
    private javax.swing.JTextArea Reg;
    private javax.swing.JMenuItem Salvar;
    private javax.swing.JLabel Title;
    private javax.swing.JMenuItem clrEditor;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
