package progsistemas;




import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Meu computador
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        EditorPane = new javax.swing.JTextPane();
        EditorExe = new javax.swing.JButton();
        EditorSave = new javax.swing.JButton();
        EditorClr = new javax.swing.JButton();
        EditorOpen = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        MacroPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MacroDef = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        MacroExp = new javax.swing.JTextArea();
        MontadorPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MontadorIn = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        MontadorOut = new javax.swing.JTextArea();
        LigadorPane = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        CodLigado = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        MaquinaPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CodCompleto = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jRegA = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jRegD = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonExe = new javax.swing.JButton();
        jButtonClr = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuHelp = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("68K Assembler Runtime Simulator");
        setResizable(false);

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jInternalFrame1.setVisible(true);

        jScrollPane10.setViewportView(EditorPane);

        EditorExe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/execute.png"))); // NOI18N
        EditorExe.setToolTipText("Executar");
        EditorExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorExeActionPerformed(evt);
            }
        });

        EditorSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/save.png"))); // NOI18N
        EditorSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorSaveActionPerformed(evt);
            }
        });

        EditorClr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/clear.png"))); // NOI18N
        EditorClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorClrActionPerformed(evt);
            }
        });

        EditorOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/open.png"))); // NOI18N
        EditorOpen.setToolTipText("Abrir no Editor");
        EditorOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditorOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditorExe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditorClr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditorSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditorOpen)
                .addContainerGap(712, Short.MAX_VALUE))
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EditorSave)
                        .addComponent(EditorClr))
                    .addComponent(EditorExe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditorOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane.addTab("Editor", jInternalFrame1);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        MacroPane.setBackground(new java.awt.Color(255, 255, 255));

        MacroDef.setEditable(false);
        MacroDef.setColumns(20);
        MacroDef.setRows(5);
        jScrollPane1.setViewportView(MacroDef);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Macros Definidas");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Macros Expandidas");

        MacroExp.setEditable(false);
        MacroExp.setColumns(20);
        MacroExp.setRows(5);
        jScrollPane6.setViewportView(MacroExp);

        javax.swing.GroupLayout MacroPaneLayout = new javax.swing.GroupLayout(MacroPane);
        MacroPane.setLayout(MacroPaneLayout);
        MacroPaneLayout.setHorizontalGroup(
            MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MacroPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addGroup(MacroPaneLayout.createSequentialGroup()
                        .addGroup(MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MacroPaneLayout.setVerticalGroup(
            MacroPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MacroPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Process. de Macros", MacroPane);

        MontadorPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Entrada do Montador");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Código Montado");

        MontadorIn.setEditable(false);
        MontadorIn.setColumns(20);
        MontadorIn.setRows(5);
        jScrollPane2.setViewportView(MontadorIn);

        MontadorOut.setEditable(false);
        MontadorOut.setColumns(20);
        MontadorOut.setRows(5);
        jScrollPane5.setViewportView(MontadorOut);

        javax.swing.GroupLayout MontadorPaneLayout = new javax.swing.GroupLayout(MontadorPane);
        MontadorPane.setLayout(MontadorPaneLayout);
        MontadorPaneLayout.setHorizontalGroup(
            MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MontadorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MontadorPaneLayout.createSequentialGroup()
                        .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(MontadorPaneLayout.createSequentialGroup()
                        .addGroup(MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 482, Short.MAX_VALUE))))
        );
        MontadorPaneLayout.setVerticalGroup(
            MontadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MontadorPaneLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Montador", MontadorPane);

        LigadorPane.setBackground(new java.awt.Color(255, 255, 255));

        CodLigado.setEditable(false);
        jScrollPane8.setViewportView(CodLigado);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Código Ligado");

        javax.swing.GroupLayout LigadorPaneLayout = new javax.swing.GroupLayout(LigadorPane);
        LigadorPane.setLayout(LigadorPaneLayout);
        LigadorPaneLayout.setHorizontalGroup(
            LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LigadorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addGroup(LigadorPaneLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 753, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LigadorPaneLayout.setVerticalGroup(
            LigadorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LigadorPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ligador", LigadorPane);

        MaquinaPane.setBackground(new java.awt.Color(255, 255, 255));

        CodCompleto.setEditable(false);
        CodCompleto.setColumns(20);
        CodCompleto.setRows(5);
        jScrollPane3.setViewportView(CodCompleto);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Código Completo");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Registradores");

        jRegA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jScrollPane9.setViewportView(jRegA);

        jRegD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jScrollPane11.setViewportView(jRegD);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("A");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("D");

        javax.swing.GroupLayout MaquinaPaneLayout = new javax.swing.GroupLayout(MaquinaPane);
        MaquinaPane.setLayout(MaquinaPaneLayout);
        MaquinaPaneLayout.setHorizontalGroup(
            MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaquinaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MaquinaPaneLayout.createSequentialGroup()
                        .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MaquinaPaneLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane11)
                            .addComponent(jScrollPane9))))
                .addContainerGap())
        );
        MaquinaPaneLayout.setVerticalGroup(
            MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaquinaPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(29, 29, 29)
                .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaquinaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carregador", MaquinaPane);

        jTabbedPane.addTab("      Processos      ", jTabbedPane1);

        jButtonExe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/open.png"))); // NOI18N
        jButtonExe.setToolTipText("Abrir e Executar");
        jButtonExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExeActionPerformed(evt);
            }
        });

        jButtonClr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/buttons/reset.png"))); // NOI18N
        jButtonClr.setToolTipText("Resetar");
        jButtonClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClrActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progsistemas/img/68kas_logo2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClr)
                .addGap(33, 33, 33))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClr)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonExe.getAccessibleContext().setAccessibleName("Abrir");
        jButtonExe.getAccessibleContext().setAccessibleDescription("Abrir");

        jMenu1.setText("Arquivo");

        MenuSair.setText("Sair");
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");

        MenuHelp.setText("Ajuda");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });
        jMenu2.add(MenuHelp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExeActionPerformed
        Principal p = null;
        
        //Leitura do nome do arquivo
        String arq = JOptionPane.showInputDialog(null, "Digite o nome do arquivo de entrada sem '.txt'", "Arquivo", JOptionPane.QUESTION_MESSAGE);
        while (/*arq != null || */ arq.equals("")) {
            arq = JOptionPane.showInputDialog(null, "Digite novamente o nome do arquivo de entrada", "Erro: nome inválido", JOptionPane.ERROR_MESSAGE);
        }
        
        //Puxar o arquivo do novo endereço para a classe Principal
        try {
            p = new Principal(arq);
        } catch (IOException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MontadorIn.setText("");
        MontadorOut.setText("");
        MacroDef.setText("");
        MacroExp.setText("");
        CodLigado.setText("");
        CodCompleto.setText("");
        jRegA.setText("");
        jRegD.setText("");
        
        MontadorIn.setText(p.getInArq());
        MontadorOut.setText(p.getOutArq());
        MacroDef.setText(p.getMacroDef());
        MacroExp.setText(p.getMacroExp());
        CodLigado.setText(p.getLigado());
        CodCompleto.setText(p.getCarregado());
        jRegA.setText(p.getRegA());
        jRegD.setText(p.getRegD());
        
    }//GEN-LAST:event_jButtonExeActionPerformed

    private void jButtonClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClrActionPerformed
        MontadorIn.setText("");
        MontadorOut.setText("");
        MacroDef.setText("");
        MacroExp.setText("");
        CodLigado.setText("");
        CodCompleto.setText("");
        jRegA.setText("");
        jRegD.setText("");
    }//GEN-LAST:event_jButtonClrActionPerformed

    private void EditorExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorExeActionPerformed
        JOptionPane.showMessageDialog(null, "Função indisponivel no momento", "Atenção", JOptionPane.ERROR_MESSAGE);
        /*String instr = EditorPane.getText();
        
        if(instr.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sem instrucoes para processar. Favor digitar o codigo", "Erro: sem instrucoes", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Principal p = null;
            String arqPath = "aux_exec";
            try {
                Save s = new Save(instr, arqPath);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                p = new Principal(arqPath);
                JOptionPane.showMessageDialog(null, "Codigo executado com exito", "Executado", 1, null);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            MontadorIn.setText("");
            MontadorOut.setText("");
            MacroDef.setText("");
            MacroExp.setText("");
            CodCarregado.setText("");
            CodLigado.setText("");
            CodCompleto.setText("");
            jRegA.setText("");
            jRegD.setText("");
            
            MontadorIn.setText(p.getInArq());
            MontadorOut.setText(p.getOutArq());
            CodLigado.setText(p.getLigado());
            jRegA.setText(p.getRegA());
            jRegD.setText(p.getRegD());
            
        }*/
    }//GEN-LAST:event_EditorExeActionPerformed

    private void EditorClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorClrActionPerformed
        EditorPane.setText("");
    }//GEN-LAST:event_EditorClrActionPerformed

    private void EditorSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorSaveActionPerformed
        String instr = EditorPane.getText();
        
        if(instr.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sem instrucoes para processar. Favor digitar o codigo", "Erro: sem instrucoes", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Principal p = null;
            String arqPath = JOptionPane.showInputDialog(null, "Digite o nome do arquivo sem '.txt'", "Salvar", JOptionPane.QUESTION_MESSAGE);
            
            Save s = null;
            try {
                s = new Save(instr, arqPath);
                JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso!", "Salvo", 1, null);
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
    }//GEN-LAST:event_EditorSaveActionPerformed

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        Help help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void EditorOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditorOpenActionPerformed
        Principal p = null;

        //Leitura do nome do arquivo
        String arq = JOptionPane.showInputDialog(null, "Digite o nome do arquivo sem '.txt'", "Arquivo", JOptionPane.QUESTION_MESSAGE);
        while (/*arq != null || */ arq.equals("")) {
            arq = JOptionPane.showInputDialog(null, "Digite novamente o nome do arquivo de entrada", "Erro: nome inválido", JOptionPane.ERROR_MESSAGE);
        }

        //Puxar o arquivo do novo endereço para a classe Principal
        try {
            p = new Principal(arq);
        } catch (IOException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        EditorPane.setText(p.getInArq());
    }//GEN-LAST:event_EditorOpenActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        dispose();
    }//GEN-LAST:event_MenuSairActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JOptionPane.showMessageDialog(null, "Simulador do Motorola 68k v. 1.0", "Bem-vindo!", 1, null);
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CodCompleto;
    private javax.swing.JTextPane CodLigado;
    private javax.swing.JButton EditorClr;
    private javax.swing.JButton EditorExe;
    private javax.swing.JButton EditorOpen;
    private javax.swing.JTextPane EditorPane;
    private javax.swing.JButton EditorSave;
    private javax.swing.JPanel LigadorPane;
    private javax.swing.JTextArea MacroDef;
    private javax.swing.JTextArea MacroExp;
    private javax.swing.JPanel MacroPane;
    private javax.swing.JPanel MaquinaPane;
    private javax.swing.JMenuItem MenuHelp;
    private javax.swing.JMenuItem MenuSair;
    private javax.swing.JTextArea MontadorIn;
    private javax.swing.JTextArea MontadorOut;
    private javax.swing.JPanel MontadorPane;
    private javax.swing.JPanel RegTable2;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButtonClr;
    private javax.swing.JButton jButtonExe;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextPane jRegA;
    private javax.swing.JTextPane jRegD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
